config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post '/follow/:id', to: 'friendships#create', as: 'follow'
  patch '/follow/:id', to: 'friendships#update', as: 'update_follow'
  resources :users, only: [:show, :index]
  resources :restaurants, only: [:show, :index, :create] do
    resources :selections, only: [:create, :destroy]
    resources :shares, only: [:create]
  end
  get '/recommend', to: 'restaurants#new', as: 'recommend'
  get '/discover', to: 'selections#index'
  # get '/search', to: 'pages#search', as: 'search'
  get '/profile', to: 'users#profile', as: 'profile'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/about', to: 'pages#about', as: 'about'
  get '/terms', to: 'pages#terms', as: 'terms'
  get '/privacy', to: 'pages#privacy', as: 'privacy'
  get '/cookies', to: 'pages#cookies', as: 'cookies'
end

app/views/shared/_banner.html.erb
<div class="bia-banner mb-4" style="background-image: linear-gradient(to bottom, rgba(242, 242, 242, 0.1), rgba(242, 242, 242, 0.1)), url(<%=asset_path('banner.png')%>)">
  <div class="container-bia d-flex align-items-end">
    <div class="banner-text-alignement">
      <h1 class="mb-2">Friendly Recommendations</h1>
      <h3 class="mb-2">Find the Restaurants that fit your taste by connecting with the people you trust</h3>
      <%= link_to "Discover restaurants!", discover_path, class: "bia-button-highlight"%>
    </div>
  </div>
  <div class="bottom-cut d-flex align-items-end">
    <svg width="100%" height="40" viewBox="0 0 800 400" preserveAspectRatio="none">
      <path d="M 0 0 C 0 0 0 0 250 400 C 350 400 800 0 800 0 L 800 400 L 0 400 L 0 000 A 50 50 0 1 1" fill="white"></path>
    </svg>
  </div>
</div>

app/views/shared/_card.html.erb
<%if data[:new] %>
  <% restaurant = data[:restaurant] %>
  <%= link_to(restaurants_path(name: restaurant.name, address: restaurant.address, placeid: restaurant.placeid, external_photo: restaurant.external_photo ), method: :post) do  %>
    <%= render 'shared/default_card', data: data %>
  <% end %>
<%elsif data[:existing_reccord]%>
  <%= link_to restaurant_path(data[:restaurant], new: true) do  %>
    <%= render 'shared/default_card', data: data %>
  <% end %>
<%else%>
  <%= link_to(data[:restaurant]) do  %>
    <%= render 'shared/default_card', data: data %>
  <% end %>
<%end%>

app/views/shared/_default_card.html.erb
<!--Default restaurant Card-->
<div class="card-bia">
  <% if !data[:restaurant].avg_occasion.nil? %>
      <p class="tag-hide" ><%= render 'shared/display_avg_occasion_text', average: data[:restaurant].avg_occasion %></p>
  <% end %>
  <% if !data[:new] %>
    <%= render 'shared/restaurants/bookmark_button_round', restaurant: data[:restaurant] %>
  <% end %>
  <%if data[:restaurant].external_photo %>
    <div class="card-image d-flex align-items-end" style="background-image: linear-gradient(to bottom, rgba(242, 242, 242, 0.1), rgba(242, 242, 242, 0.1)), url('<%=data[:restaurant].external_photo%>')">
  <% else %>
    <div class="card-image d-flex align-items-end" style="background-image: linear-gradient(to bottom, rgba(242, 242, 242, 0.1), rgba(242, 242, 242, 0.1)), url('<%= cl_image_path data[:restaurant].photo %>')">
  <% end %>
    <svg width="100%" height="8" viewBox="0 0 800 400" preserveAspectRatio="none">
      <path d="M 0 0 C 0 0 0 0 250 400 C 350 400 800 0 800 0 L 800 400 L 0 400 L 0 000 A 50 50 0 1 1" fill="#F2F2F2"></path>
    </svg>
  </div>
  <div class="px-3 pb-2 pt-2 default-card-content">
    <!-- Card Information box -->
      <div class="d-flex justify-content-between align-items-center pb-2 height-25-px">

        <!-- Card Information top row-->
        <!-- Restaurant name -->
        <div class="d-flex align-items-center">
          <h5 class="h5-style"><%=data[:restaurant].name.truncate(33)%></h5>
        </div>

        <!-- Friend imgs -->
        <div class="d-flex align-items-center">
          <%array_of_friends = data[:restaurant].get_friends_recommended(current_user).reject{|selection| selection.user == data[:user_to_exclude]}%>
          <%if array_of_friends.any? %>
            <%number_of_friends = array_of_friends.count %>
            <% array_of_friends.sample(3).each_with_index do |selection, count| %>
                <div class="avatar-very-small image-overlay-left" data-tooltip="<%=selection.user.name%>" style="background-image: url('<%= cl_image_path selection.user.photo %>')"></div>
            <% end %>
          <%end%>
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <!-- Card Information bottom row-->
        <% if data[:disp_address] %>
          <p><%=data[:restaurant].address.truncate(40)%></p>
        <% else %>
          <p><%=data[:restaurant].cuisine%></p>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_discover_elements_friendships.html.erb
<div class="discover-activity-card">
  <%= link_to(user_path(friendship.asker)) do %>
    <div class="avatar-large" style="background-image: url('<%= cl_image_path friendship.asker.photo %>')"></div>
  <% end %>
  <div class="activity-content">
    <h5> <%= link_to friendship.asker.name, friendship.asker %> has started following you </h5>
    <%= render 'shared/friendships/mutual_followers', mutual_followers: mutual_followers, friendship: friendship, small: false %>
    <p class="small-font mt-2"> Started following you on <%= friendship.created_at.strftime('%a %d %b %Y') %></p>
  </div>
</div>

app/views/shared/_discover_elements_selections.html.erb
<% if selection.recommended? %>
  <div class="discover-activity-card">
    <%= link_to(user_path(selection.user)) do %>
      <div class="avatar-large" style="background-image: url('<%= cl_image_path selection.user.photo %>')"></div>
    <% end %>
    <div class="activity-content">
      <%= render 'shared/review_header', selection: selection, restaurant_show: false%>
      <p class="my-2"> <%= selection.review %> </p>
      <%= render 'shared/card', data: {restaurant: selection.restaurant, user_to_exclude: selection.user}%>
      <p class="small-font mt-3"> Posted on <%= selection.created_at.strftime('%a %d %b %Y') %></p>
    </div>
  </div>

<% elsif selection.bookmarked? %>
  <div class="discover-activity-card">
    <%= link_to(user_path(selection.user)) do %>
      <div class="avatar-large" style="background-image: url('<%= cl_image_path selection.user.photo %>')"></div>
    <% end %>
    <div class="activity-content">
      <h5 class="mb-2"> <%= link_to selection.user.name, selection.user%> has bookmarked <%= link_to selection.restaurant.name, restaurant_path(selection.restaurant), class: 'text-color-black'%></h5>
      <%= render 'shared/card', data: {restaurant: selection.restaurant} %>
      <p class="small-font mt-3"> Bookmarked on <%= selection.created_at.strftime('%a %d %b %Y') %></p>
    </div>
  </div>
<% end %>

app/views/shared/_display_avg_occasion_text.html.erb
<% if average == 1 %>
  on-the-go
<%  elsif average == 2 %>
  casual
<% elsif average == 3 %>
  evening out
<% elsif average == 4 %>
  fine dining
<% end %>

app/views/shared/_display_avg_price.html.erb
<% if average == 1 %>
  <span> € </span>
<% elsif average == 2 %>
  <span> €€ </span>
<% elsif average == 3 %>
  <span> €€€ </span>
<% elsif average == 4 %>
  <span> €€€€</span>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-bia-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-bia-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_input_occasion.html.erb
<h5 class="mb-2">Occasion</h5>
<div class="bia-radio-button bia-radio-button-width-adaptive mb-2">
  <%= f.input_field :occasion,
              as: :radio_buttons,
              collection: [[1, 'on-the-go'], [2, 'casual'], [3, 'evening out' ], [4, 'fine dining']],
              label_method: :second,
              value_method: :first %>
</div>

app/views/shared/_map.html.erb
<div
  id="map"
  style="width: 100%;
  height: 70vh;"
  data-markers="<%= @markers.to_json %>"
  class = "width-100-pc span-2-1 image-rounded-corners"
></div>

app/views/shared/_modal_recommend.html.erb
<div class="bia-modal" id='recommend-modal'>

  <div class="modal-review-content">
    <i class="fas fa-times modal-close close-button"></i>
    <div class = "modal-core-window">
      <div id="rcmd-form">
        <%= render 'selections/recommendation_form', restaurant: restaurant, selection: selection%>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-bottom-border">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon container-bia-navbar py-2 px-0">
    <div class="d-flex align-items-center">
      <h1 class="mr-5 my-0"><%= link_to "BIA", discover_path, class: "navbar-logo"%></h1>
      <% if user_signed_in? %>
        <h5 class="mr-3 my-0"><%= link_to "Find", restaurants_path, class: "navbar-link"%></h4>
        <h5 class="my-0"><%= link_to "Profile", user_path(current_user), class: "navbar-link"%></h4>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="">
            <%= link_to "Recommend", recommend_path, class: "bia-button-highlight" %>
          </li>
          <li class="nav-item dropdown ml-3">
            <% if current_user.photo? %>
              <%= cl_image_tag current_user.photo, class: "tool_image", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <% else %>
              <%= cl_image_tag 'profile_picture_unavailable_gwyjic', class: "tool_image", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Account", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
            </li>
            <% else %>
              <li class="nav-item">
                <h5 class="my-0"><%= link_to "Login", new_user_session_path, class: "navbar-link" %></h5>
              </li>
            <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pageinator.html.erb
<div>
  <%if total_pages >= 2%>
    <div  class="pages-selection-row">
      <% prev_path = path_to_prev_page elements %>
      <%= link_to prev_path, class: "biabutton button-svg" do %>
        <svg width="12" height="21" viewBox="0 0 12 21" xmlns="http://www.w3.org/2000/svg">
          <path d="M1.19161 9.16705C0.513015 9.92613 0.513013 11.0739 1.1916 11.8329L8.50894 20.0182C9.73276 21.3872 12 20.5215 12 18.6853V2.3147C12 0.478447 9.73276 -0.387221 8.50894 0.981759L1.19161 9.16705Z"/>
        </svg>
      <%end %>
      <p class="pages-counter"><%=current_page%>/<%=total_pages%></p>
      <% next_path = path_to_next_page elements %>
      <%= link_to next_path, class: "biabutton button-svg" do %>
        <svg width="12" height="21" viewBox="0 0 12 21" xmlns="http://www.w3.org/2000/svg">
          <path class="" d="M10.8084 11.8329C11.487 11.0739 11.487 9.92614 10.8084 9.16705L3.49106 0.98176C2.26724 -0.38722 0 0.478452 0 2.31471L0 18.6853C0 20.5216 2.26724 21.3872 3.49106 20.0182L10.8084 11.8329Z"/>
        </svg>
      <%end %>
    </div>
  <% end %>
  <!-- <div class="pages-selection-row"> -->
    <!-- <p><%#= #@restaurants.count %> places found for you</p> -->
  <!-- </div> -->
</div>

app/views/shared/_review_header.html.erb
<h5>
  <% if restaurant_show == true %>
    <%= selection.user.name  %>
  <% else %>
    <%= link_to selection.user.name, selection.user%>
    recommended
    <%= link_to selection.restaurant.name, restaurant_path(selection.restaurant), class: 'text-color-black'%>
  <% end %>
  <% if restaurant_show == true %>
    <span class="p-style">
      <% if selection.occasion == 1 %>
        – on-the-go
      <% elsif selection.occasion == 2 %>
        – casual
      <% elsif selection.occasion == 3 %>
        – evening out
      <% elsif selection.occasion == 4 %>
        – fine dining
      <% end %>
    </span>
  <% else %>
  for
    <% if selection.occasion == 1 %>
      eating on-the-go
    <% elsif selection.occasion == 2 %>
      a casual occasion
    <% elsif selection.occasion == 3 %>
      an evening out
    <% elsif selection.occasion == 4 %>
      fine dining
    <% end %>
  <% end %>
</h5>