config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post '/follow/:id', to: 'friendships#create', as: 'follow'
  patch '/follow/:id', to: 'friendships#update', as: 'update_follow'
  resources :users, only: [:show, :index]
  resources :restaurants, only: [:show, :index, :create] do
    resources :selections, only: [:create, :destroy]
    resources :shares, only: [:create]
  end
  get '/recommend', to: 'restaurants#new', as: 'recommend'
  get '/discover', to: 'selections#index'
  # get '/search', to: 'pages#search', as: 'search'
  get '/profile', to: 'users#profile', as: 'profile'
  get '/contact', to: 'pages#contact', as: 'contact'
  get '/about', to: 'pages#about', as: 'about'
  get '/terms', to: 'pages#terms', as: 'terms'
  get '/privacy', to: 'pages#privacy', as: 'privacy'
  get '/cookies', to: 'pages#cookies', as: 'cookies'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  searchkick word_middle: [:cuisine, :name, :recommended], locations: [:location], suggest: [:name, :cuisine, :recommended]
  scope :search_import, -> { includes(:selections, :users) }
  has_many :selections, dependent: :destroy
  has_many :users, through: :selections
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :shares, dependent: :destroy
  has_many :users_sharing, through: :shares, foreign_key: :user_id

  mount_uploader :photo, PhotoUploader

  CUISINES = ['Italian', 'Asian-inspired', 'Vietnamese', 'German', 'Pizza', 'Fast Food',
  'Breakfast & Brunch', "Pan Asian", "Kebab", "Burgers", "Sushi Bars", "Mediterranean", "Indian", "Turkish",
  "Chinese", "Bakeries", "Coffee & Tea", "Thai", "Middle Eastern", "Greek", "Steak", "French",
  "Patisserie / Cake Shop", "Vegan", "Sandwiches", "Modern European", "Ice Cream & Frozen Yogurt", "Korean",
  "Mexican", "Japanese", "Arabian", "Salad", "Vegetarian", "Barbeque", "Falafel", "Spanish", "Lebanese",
  "Austrian", "Seafood", "Soup", "Tapas", "American", "Buffets", "Creperies", "Waffles", "Asian Fusion", "Russian",
  "Argentine", "Latin American", "Wine Bars", "Cajun" , "Caribbean", "Moroccan", "Swedish", "Latvian", "Scottish",
  "British", "Russian", "Jewish", "Canadian", "Polish", "Hawaiian", "Brazilian", "Peruvian", "Salvadorian",
  "Cuban", "Tibetan", "Egyptian", "Belgian", "Irish", "Welsh", "Mormon", "Portuguese", "Haitian",
  "Tahitian", "Kenyan", "Algerian", "Nigerian", "Libyan", "Syrian"]

  def search_data
    { name: name,
      cuisine: cuisine,
      recommended: "#{users.map(&:name).join(' ')}",
      price: avg_price,
      occasion: avg_occasion,
      popularity: self.selections.count
    }.merge(location: {lat: latitude, lon: longitude})
  end

  def get_friends_recommended(user)
    selections = self.selections.where(recommended: true)
    selections.where(user: User.following(user, "instance"))
  end

  def self.relevant_restaurants(user, type)
    Restaurant.reciever_restaurants(user, type) + Restaurant.user_restaurants(user, type)
  end

  def self.reciever_restaurants(user, type)
    receivers = User.following(user, "instance")
    all_selections = []
    restaurants = []
    receivers.each { |receiver| all_selections << receiver.selections }
    all_selections.each do |user_selections|
      user_selections.each do |selection|
        restaurants << selection.restaurant if selection.recommended == true
      end
    end
    Restaurant.type_conversion(restaurants, type)
  end

  def self.user_restaurants(user, type)
    Restaurant.user_restaurants_recommended(user, type) + Restaurant.user_restaurants_bookmarked(user, type)
  end

  def self.user_restaurants_recommended(user, type)
    restaurants = []
    user.selections.each do |selection|
      restaurants << selection.restaurant if selection.recommended == true
    end
    Restaurant.type_conversion(restaurants, type)
  end

  def self.user_restaurants_bookmarked(user, type)
    restaurants = []
    user.selections.each do |selection|
      restaurants << selection.restaurant if selection.bookmarked == true
    end
    Restaurant.type_conversion(restaurants, type)
  end

  def calc_avg_occassion
    all_selections = self.selections.where(recommended: true)
    all_occassions = 0
    all_selections.each do |selection|
      if !selection.occasion.nil?
        all_occassions += selection.occasion
      end
    end
    self.avg_occasion = (all_occassions.to_f / all_selections.length).round
    self.save
  end

  def calc_avg_price
    p self.name
    all_selections = self.selections.where(recommended: true)
    all_prices = 0
    all_selections.each do |selection|
      if !selection.price.nil?
        p all_prices += selection.price
      end
    end
    self.avg_price = (all_prices.to_f / all_selections.length).round
    p self.avg_price
    self.save
  end

  def calc_most_common_cuisine
    self.name
    count_by_cuisine = self.selections.group(:cuisine).count
    count_by_cuisine
    highest_value = count_by_cuisine.max_by{|k,v| v}[1]
    highest_value
    cuisines = count_by_cuisine.select { |key, value| value == highest_value }.keys
    cuisines
    cuisine_tag = ''
    cuisines.each do |cuisine|
      if !cuisine.nil? && cuisine != ""
        cuisine_tag += "#{cuisine}, "
      end
    end
    self.cuisine = cuisine_tag.chomp(", ")
    self.save
  end

  private

  def self.type_conversion(restaurants, type)
    if type == "id"
      return restaurants.map!{ |restaurant| restaurant.id }
    elsif type == "instance"
      return restaurants
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index

    if params[:search].presence
      search_params[:query].presence ? query = search_params[:query].unicode_normalize(:nfkd).encode('ASCII', replace: '') : query = "*"
    else
      query = "*"
    end
    @user_location = params[:search].presence ? location_coords : {latitude: current_user.latitude, longitude:current_user.longitude}
    options = { fields: ["name^10", "cuisine^2", :recommended], suggest: true, per_page: 24, operator: "or", match: :word_middle, page: params[:page]}
    options[:where] = where
    options[:boost_by_distance] = boost_by_distance

    # keep for user search
    # options = {fields: [:name, :cuisine, :recommended, :friendname, :username, :email], operator: "or", match: :word_middle}
    # @your_users = policy_scope(User).search(search_query, options)
    @restaurants = policy_scope(Restaurant).search(query, options)
    @current_user = current_user
    @current_page = @restaurants.current_page
    @total_pages = @restaurants.total_pages
    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: { content: render_to_string(partial: "/shared/map_popup", locals: { data: { restaurant: restaurant, color: "FFFFFF" } }) }
      }
    end
    respond_to do |format|
      format.html { render 'index' }
      format.js
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @new_recommendation = Selection.new
    @markers = [{
      lat: @restaurant.latitude,
      lng: @restaurant.longitude,
      infoWindow: { content: render_to_string(partial: "/shared/card", locals: { data: { restaurant: @restaurant } }) }
    }]
    @reviews = Selection.where(user: current_user, restaurant: @restaurant).or(Selection.where(user: User.following(current_user, "instance"), restaurant: @restaurant)).order(updated_at: :desc)
    @share = Share.new()
    @new = params[:new]
    if !Selection.find_by(user: current_user, restaurant: @restaurant, recommended: "true").nil?
      @new = false
    end
  end

  def new
    @restaurant = Restaurant.new()
    authorize @restaurant
    @results = []
    # check if search query was executed by the user
    if params[:search].presence
      search_query = search_params[:query].unicode_normalize(:nfkd).encode('ASCII', replace: '')
      location = location_coords
      if location[:longitude] != 'na'
        # use search input to find places using google api
        nearby_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{location[:latitude]},#{location[:longitude]}&radius=#{location[:range]}&type=restaurant&keyword=#{search_query}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
        json_sereialized = JSON.parse(open(nearby_url).read)
        json_sereialized["results"].each do |result|
          # incase google does not provide a photo set photo to nil to avoid method error
          if result["photos"]
            photo = result["photos"][0]
          else
            photo = nil
          end
          @results << [result["name"], result["vicinity"], result["place_id"], photo]
        end
      # if no location was found using the browser and nothing was given in the location field,
      # do a text search which does not require a location
      else
        location_string = user_default_location
        # execute google places text search
        text_url = "https://maps.googleapis.com/maps/api/place/textsearch/json?query=#{search_query}&#{location_string}type=restaurant&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
        json_sereialized_text = JSON.parse(open(text_url).read)
        json_sereialized_text["results"].each do |result|
          if result["photos"]
            photo = result["photos"][0]
          else
            photo = nil
          end
          @results << [result["name"], result["formatted_address"], result["place_id"], photo]
        end
      end

      # check if the restaurant exists in the database if not create a new instace to show to the user
      @results.map! do |result|
        database_record = Restaurant.where(placeid: result[2])
        if database_record != []
          {restaurant: database_record[0], existing_reccord: true}
        else
          if result[3].present?
            photos_url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=#{result[3]["photo_reference"]}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
          else
            photos_url = "https://images.unsplash.com/photo-1505935428862-770b6f24f629?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1947&q=80"
          end
          { restaurant:
            Restaurant.new(
              name: result[0],
              address: result[1],
              external_photo: photos_url,
              placeid: result[2]
            ),
            existing_reccord: false }
        end
      end
    end
    @results = Kaminari.paginate_array(@results).page(params[:page]).per(18)
    @current_page = @results.current_page
    @total_pages = @results.total_pages
    @six_recent = Share.recents(current_user)
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    authorize @restaurant
    details_url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=#{restaurant_params["placeid"]}&fields=formatted_phone_number,website&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
    json_sereialized = JSON.parse(open(details_url).read)
    @restaurant.phone_number = json_sereialized["result"]["formatted_phone_number"] if json_sereialized["result"]["formatted_phone_number"]
    @restaurant.url = json_sereialized["result"]["website"] if json_sereialized["result"]["website"]
    if @restaurant.save
      redirect_to restaurant_path(@restaurant, new: true)
    else
      render :new
    end
  end

  private

  def convert_location(location)
    Geocoder.search(search_params[:location]).first.coordinates
  end

  def where
    where = {id: Restaurant.relevant_restaurants(current_user, "id")}
    if params[:search].present?
      if params[:search][:location].present?
        location = location_coords
        if location != 'na'
          where[:location] = {near: {lat: location[:latitude], lon: location[:longitude]}, within: "#{location[:range]/1000}km"}
        end
      end
      if search_params[:cuisine].present? && search_params[:cuisine][1].present?
        where[:cuisine] = search_params[:cuisine].drop(1)
      end
      if search_params[:occasion].present? && search_params[:occasion][1].present?
        where[:occasion] = search_params[:occasion].drop(1)
      end
      if search_params[:price].present? && search_params[:price][1].present?
        where[:price] = search_params[:price].drop(1)
      end
    end
    where
  end

  def boost_by_distance
    boost = {}
    if params[:search].presence
      location = location_coords
      if location[:latitude] != 'na'
        boost[:location] = {origin: {lat: location[:latitude], lon: location[:longitude]}}
      end
    end
    boost
  end

  def location_coords
    if search_params[:long].present?
      longitude = search_params[:long]
      latitude = search_params[:lat]
    else
      longitude = 'na'
      latitude = 'na'
    end
    range = 5000

    # check if a location was provided by the user,
    # if true the location determined by the browser is overwritten
      if search_params[:location].present?
        coordinates = convert_location(search_params[:location])
        latitude = coordinates[0]
        longitude = coordinates[1]
      end

      if longitude != 'na'
        # check if a range was given by the user, othwerwise the default of 5000 is used
        if search_params[:range].present?
          range = search_params[:range].to_i * 1000
        end
      end

    { longitude: longitude, latitude: latitude, range: range }
  end

  def user_default_location
    # Providing some location reference improves results though, therefore check if the user has
    # set a home location on their profile, use it to improve search results
    if current_user.location.present?
      location_string = "location=#{current_user.latitude},#{current_user.longitude}&radius=#{50000}&"
    else
      location_string = ''
    end
  end

  def search_params
    params.require(:search).permit(:query, :lat, :long, :location, :range, :cuisine => [], :occasion => [], :price => [])
  end

  def restaurant_params
    params.permit(:address, :external_photo, :name, :placeid)
  end
end

app/views/shared/restaurants/_actionbuttons.html.erb
<button class="quick-action block" id="open-share-modal">Share</button>
<% if !restaurant.reservation.nil? && restaurant.reservation != "" %>
  <%= link_to "Make a reservation", restaurant.reservation, target: "_blank", class: "quick-action block"  %>
<% end %>
<% if !restaurant.menu.nil? && restaurant.menu != "" %>
  <%= link_to "See the menu", restaurant.menu, target: "_blank", class: "quick-action block"  %>
<% end %>
<%= link_to "Suggest an edit", contact_path , target: "_blank", class: "quick-action block"  %>

app/views/shared/restaurants/_bookmark_button.html.erb
<% selection = Selection.find_by(user: current_user, restaurant: restaurant) %>
<% bookmarked = selection.bookmarked if !selection.nil?%>

<%= link_to(restaurant_selections_path(restaurant, bookmark: true), method: :post, remote: true, id: "bookmark", class: "size-48-pc biabutton-thin#{" biabutton-thin-active" if bookmarked} font-size-awesome text-center") do %>
  <i class='fas fa-bookmark'></i>
  <p class="small-font bookmark-explanation">bookmark<%= "ed" if bookmarked %></p>
<% end %>

app/views/shared/restaurants/_bookmark_button_round.html.erb
<% selection = Selection.find_by(user: current_user, restaurant: restaurant) %>
<% bookmarked = selection.bookmarked if !selection.nil?%>

<div data-restaurant-id="<%= restaurant.id %>">
  <%= button_to(restaurant_selections_path(restaurant, bookmark_round: true), action: "create", remote: true, class: "round-bookmark biabutton-round#{" biabutton-round-active" if bookmarked} font-size-awesome text-center") do %>
    <i class='fas fa-bookmark'></i>
  <% end %>
</div>

app/views/shared/restaurants/_corebuttons.html.erb
<% selection = Selection.find_by(user: current_user, restaurant: restaurant) %>
<% bookmarked = selection.bookmarked if !selection.nil?%>
<%recommended = selection.recommended if !selection.nil? %>

<div class="width-100-pc d-flex justify-content-between">
  <%= render 'shared/restaurants/recommend_button', restaurant: restaurant, selection: recommendation%>
  <%= render 'shared/restaurants/bookmark_button', restaurant: restaurant, recommendation: recommendation%>
</div>

app/views/shared/restaurants/_filter.html.erb
  <%query = params[:search][:query] if !params[:search].nil?%>
  <%location = params[:search][:location] if !params[:search].nil?%>
  <%cuisine = params[:search][:cuisine] if !params[:search].nil?%>
  <%occasion = params[:search][:occasion] if !params[:search].nil?%>
  <%price = params[:search][:price] if !params[:search].nil?%>
  <div class="hide" id="user-location-determine">
    <%= render 'shared/restaurants/location_field', user_location: @user_location%>
  </div>
  <%= simple_form_for :search, url: restaurants_path, method: "GET", html: { class: 'form-remove-b-margin', id: 'autosubmit-form' }, remote: true do |f| %>
      <%=f.input :query, required: false, label: false, placeholder: "Restaurant name, cuisine...", input_html: {class: 'input-field simple_form-align mb-2', value: query}%>
      <h5 class="mb-2">Location</h5>
      <div class="input-field-to-row-filter">
        <%=f.input :location, required: false, label: false, placeholder: "Location of places", input_html: {class: 'input-field simple_form-align mb-2 multiselectuser', value: location}%>
        <%=f.input :range,  as: :numeric, label: false, required: false, placeholder: "5km",  input_html: {class: 'input-field' }%>
      </div>
      <%=f.input :lat, required: false, label: false, input_html: {value: 'na', class: 'hide', id: 'latitude-hidden' }%>
      <%=f.input :long, required: false, label: false, input_html: {value: 'na', class: 'hide', id: 'longitude-hidden' }%>
      <h5 class="mb-2">Cuisine</h5>
      <%=f.input :cuisine, as: :select, collection: Restaurant::CUISINES.sort, required: false, label: false, input_html: {data: {"live-search" => :true, "actions-box" => :true, width: '345px', style: "btn-light"}, selected: cuisine, class: 'simple_form-align mb-2 selectpicker', multiple: "", title:"French, Japanese, Italian..."}%>
      <h5 class="mb-2">Occasion</h5>
      <div class="bia-radio-button bia-radio-button-width-filter mb-2">
        <%= f.input_field :occasion,
                    checked: occasion,
                    as: :check_boxes,
                    collection: [[1, 'on-the-go'], [2, 'casual'], [3, 'evening out' ], [4, 'fine dining']],
                    label_method: :second,
                    value_method: :first %>
      </div>
      <h5 class="mb-2">Price</h5>
      <div class="bia-radio-bar mb-2">
        <%= f.input_field :price,
                  checked: price,
                  as: :check_boxes,
                  collection: [[1, '€'], [2, '€€'], [3, '€€€' ], [4, '€€€€']],
                  label_method: :second,
                  value_method: :first%>
      </div>
    <button type="submit" class="biabutton width-75px mr-3" id="filter-submit"><i class="fas fa-search"></i></button>
    <%= link_to 'Reset', restaurants_path(reset: true), class:"biabutton width-75px text-align-center", id:"index-filter-reset"%>
  <% end %>

app/views/shared/restaurants/_location_field.html.erb
<span class="hide" id="user-det-location" data-lat="<%=@user_location[:latitude]%>" data-long="<%=@user_location[:longitude]%>"></span>

app/views/shared/restaurants/_recommend_button.html.erb
<% selected = Selection.find_by(user: current_user, restaurant: restaurant) %>
<%recommended = selected.recommended if !selected.nil? %>
<button class ="biabutton-thin<%=" biabutton-thin-active" if recommended%> size-48-pc font-size-awesome" <%='disabled' if recommended%> id="open-modal">
  <i class="fas fa-bullhorn"></i>
  <p class="small-font recommend-explanation"> recommend<%= "ed" if recommended %></p>
</button>

app/views/shared/restaurants/_restaurant_card_grid.html.erb
<div class="index-restaurants-grid">
  <% if defined?(user_to_exclude) %>
    <% if restaurants.first.nil? %>
      <div class="span-2-1">
        <h4>Ooops! No Places found.</h4>
        <p>You should <%= link_to 'recommend', recommend_path %> something or <%= link_to 'add a friend!', users_path %></p>
      </div>
    <% else %>
      <% restaurants.each do |restaurant| %>
          <%= render 'shared/card', data: {restaurant: restaurant, user_to_exclude: user_to_exclude}%>
      <% end %>
    <% end %>
  <% else %>
    <% if restaurants.first.nil? %>
      <div class="span-2-1">
        <h4>Ooops! No Places found.</h4>
        <p>You should <%= link_to 'recommend', recommend_path %> something or <%= link_to 'add a friend!', users_path %></p>
      </div>
    <% else %>
      <% restaurants.each do |restaurant| %>
        <%= render 'shared/card', data: {restaurant: restaurant}%>
      <% end %>
    <% end %>
  <% end %>
</div>
<%= render 'shared/pageinator', elements: restaurants, current_page: current_page, total_pages: total_pages %>

app/views/shared/restaurants/_restaurantdetails.html.erb
<div id="restaurant-details">


<% if (restaurant.cuisine != "" && !restaurant.cuisine.nil?) || (restaurant.avg_occasion != "" && !restaurant.avg_occasion.nil?) || (restaurant.avg_price != "" && !restaurant.avg_price.nil?) %>
  <h5 class = 'mt-4'>Restaurant details </h5>
  <p class="p-style small-font mb-3 "> based on <%= [1, restaurant.selections.where(recommended:true).count].max { |a, b| a<=>b}  %> reviews </p>
  <% if restaurant.cuisine != "" && !restaurant.cuisine.nil? %>
    <p class= 'my-2 details-cuisine'> Cuisine: <%= restaurant.cuisine %></p>
  <% end %>
  <% if restaurant.avg_occasion != "" && !restaurant.avg_occasion.nil? %>
    <p class= 'my-2 details-occassion'> Mostly suited for: <%= render 'shared/display_avg_occasion_text', average: restaurant.avg_occasion %></p>
  <% end %>
  <% if restaurant.avg_price != "" && !restaurant.avg_price.nil? %>
    <p class= 'my-2 details-price'> Prices: <%= render 'shared/display_avg_price', average: restaurant.avg_price %></p>
  <% end %>
<% end %>

<h5 class = 'mb-3 mt-4'>Contact details</h5>
  <p class= 'my-2'> Address: <%= restaurant.address %></p>
  <% if restaurant.phone_number != '' && !restaurant.phone_number.nil? %>
    <p class= 'my-2'> Phone: <%= restaurant.phone_number %></p>
  <% end %>
  <% if restaurant.email != '' && !restaurant.email.nil?%>
    <p class= 'my-2'> E-mail: <a href=<%= "mailto:#{restaurant.email}" %>> <%= restaurant.email %> </a>  </p>
  <% end %>
  <% if restaurant.url != '' && !restaurant.url.nil? %>
    <p class= 'my-2'> Web: <a href=<%= restaurant.url %> target="_blank"> <%= restaurant.name %> </a> </p>
  <% end %>
</div>

app/views/shared/restaurants/_review.html.erb
<div class="review-card">
  <%= link_to(user_path(selection.user)) do %>
    <div class="avatar-large review-card-avatar" style="background-image: url('<%= cl_image_path selection.user.photo %>')"></div>
  <% end %>
  <div class="core-review">
    <div class="review-header">
      <%= render 'shared/review_header', selection: selection, restaurant_show: true%>
      <p class="tag"> <%= "€"*selection.price %> </p>
    </div>
    <p class='my-1'> <%= selection.review %> </p>
    <div class="bottom-line">
      <p class="small-font mt-1"> Posted on <%= selection.updated_at.strftime('%a %d %b %Y') %></p>
      <p id="navbarDropdown", data-toggle="dropdown">
        <% if selection.user == current_user %>
          <svg width="21" class="svg-dropdown" height="12" viewBox="0 0 21 12" xmlns="http://www.w3.org/2000/svg"><path d="M9.16705 10.8084C9.92613 11.487 11.0739 11.487 11.8329 10.8084L20.0182 3.49106C21.3872 2.26724 20.5215 0 18.6853 0H2.3147C0.478447 0 -0.387221 2.26724 0.981759 3.49106L9.16705 10.8084Z"/>
        <% end %>
      </p>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <!-- <button id="open-edit-modal" class="dropdown-item">Edit</button> -->
        <%= link_to "Delete", restaurant_selection_path(@restaurant, selection), method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/restaurants/_reviewcards.html.erb
  <% @reviews.where(recommended: true).each do |selection| %>
    <%= render 'shared/restaurants/review', restaurant: @restaurant, selection: selection%>
  <% end %>